### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by regek** [free5gmano/simpleexampleplugin#1]
It seems the main code for orchestrator is updated, but not for the plugin. The orchestrator says path not found.
**_vnfpkgm/v1/vnf_packages/_**

**Comment by cewuandy** [comment]
Hello regek,
Please check your kube5gnfvo is correctly installed and you can access x.x.x.x:30888 page.
Thanks.

**Comment by regek** [comment]
Thanks, it worked.
